#!/bin/bash

LTEPI_GITHUB_ID=Robotma-com/ltepi

function assert_root {
  if [[ $EUID -ne 0 ]]; then
     echo "This script must be run as root" 
     exit 1
  fi
}

function assert_vars {
  if [ -z "${VERSION}" ]; then
    echo "VERSION is missing" 
    exit 1
  fi
  if [ -z "${LTEPI_VERSION}" ]; then
    echo "LTEPI_VERSION is missing" 
    exit 1
  fi
}

function install_cli {
  install -o root -g root -D -m 755 bin/get_iccid /opt/inn-farm/ltepi/bin/get_iccid
  install -o root -g root -D -m 755 bin/power_off /opt/inn-farm/ltepi/bin/power_off
  install -o root -g root -D -m 755 bin/power_on /opt/inn-farm/ltepi/bin/power_on
  install -o root -g root -D -m 755 bin/vbus_off /opt/inn-farm/ltepi/bin/vbus_off
  install -o root -g root -D -m 755 bin/vbus_on /opt/inn-farm/ltepi/bin/vbus_on
  install -o root -g root -D -m 755 bin/gpio_init /opt/inn-farm/ltepi/bin/gpio_init
  echo "${VERSION}" > ./bin/version.txt
  install -o root -g root -D -m 644 bin/version.txt /opt/inn-farm/ltepi/bin/version.txt

  mv /etc/network/interfaces /etc/network/interfaces.bak
  install -o root -g root -D -m 644 etc/network/interfaces /etc/network/interfaces
  mv /etc/rc.local /etc/rc.local.bak
  install -o root -g root -D -m 755 etc/rc.local /etc/rc.local
  
  cp -f uninstall.sh /opt/inn-farm/ltepi/bin/
}

function install_ltepi {
  curl -L https://github.com/${LTEPI_GITHUB_ID}/archive/${LTEPI_VERSION}.tar.gz | tar zx
  cd ltepi-${LTEPI_VERSION}
  ./install.sh /opt/inn-farm/ltepi/bin
  cd ../
  rm -rf ltepi-${LTEPI_VERSION}
}

assert_root
assert_vars
install_cli
install_ltepi
